"""Export where Mapterhorn's relief goes deeper than z12 (`web/src/terraincoverage.ts`).

Mapterhorn publishes the planet to z12 and, past that, regional archives
cut on the zoom-6 grid, each with its own deepest zoom (13 to 18). The map
asks for a deep tile only inside a cell that has one, so the rest of the
world costs no 404s. An archive of a few hundred bytes holds no tiles and
is left out.

Run by hand when Mapterhorn publishes a new release; the output is
committed.

    .venv/bin/python scripts/build_terrain_coverage.py
"""

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

SOURCE = "https://download.mapterhorn.com/download_urls.json"
USER_AGENT = "xue-terrain-coverage/1.0 (https://github.com/ringsaturn/xue)"
OUT = Path(__file__).resolve().parent.parent / "web" / "src" / "terraincoverage.ts"
CELL_ZOOM = 6
GLOBAL_MAX_ZOOM = 12
EMPTY_ARCHIVE_BYTES = 1024
NAME = re.compile(rf"^{CELL_ZOOM}-(\d+)-(\d+)\.pmtiles$")


def main() -> None:
    request = urllib.request.Request(SOURCE, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        listing = json.load(response)
    cells: dict[tuple[int, int], int] = {}
    for item in listing["items"]:
        match = NAME.match(item["name"])
        if not match or item["size"] < EMPTY_ARCHIVE_BYTES or item["max_zoom"] <= GLOBAL_MAX_ZOOM:
            continue
        key = (int(match.group(1)), int(match.group(2)))
        cells[key] = max(cells.get(key, 0), int(item["max_zoom"]))
    entries = ",".join(f"{x}/{y}/{zoom}" for (x, y), zoom in sorted(cells.items()))
    lines = [
        "// Generated by scripts/build_terrain_coverage.py; do not edit.",
        f"// Mapterhorn release {listing['version']}: {len(cells)} zoom-{CELL_ZOOM} cells, `x/y/deepest zoom`.",
        f"export const TERRAIN_COVERAGE_RELEASE = {json.dumps(listing['version'])};",
        f"export const TERRAIN_COVERAGE_CELL_ZOOM = {CELL_ZOOM};",
        f"export const TERRAIN_COVERAGE_CELLS =\n  {json.dumps(entries)};",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(cells)} cells)")


if __name__ == "__main__":
    main()
